version: "3"

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: vk_user
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: eldorado
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      DSN: "host=db user=vk_user password=changeme dbname=eldorado sslmode=disable"
    depends_on:
      - db

volumes:
  db-data:
